name: Fast CI

on:
  push:
    branches: [ main, develop ]

env:
  NODE_VERSION: 20

jobs:
  # Quick Quality & Build Check
  fast-check:
    name: Fast Quality & Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type check
        run: npx tsc --noEmit

      - name: Lint code
        run: npm run lint --if-present

      - name: Run core unit tests
        run: npm run test:run -- src/test/unit/storyEngine.test.ts src/test/unit/StoryRenderer.test.tsx src/test/unit/simpleState.test.tsx

      - name: Build application
        run: npm run build

      - name: Security audit (non-blocking)
        run: npm audit --audit-level=high || echo "⚠️ Security audit completed with warnings"

  # Fast CI Success
  fast-ci-success:
    name: Fast CI Complete
    runs-on: ubuntu-latest
    needs: [fast-check]
    if: always()
    steps:
      - name: Check Fast CI Status
        run: |
          if [ "${{ needs.fast-check.result }}" == "success" ]; then
            echo "✅ Fast CI passed - ready for deployment"
            exit 0
          else
            echo "❌ Fast CI failed"
            exit 1
          fi